services:
  - type: web
    name: smart-artisan-assistant
    runtime: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: N8N_QC_WEBHOOK_URL
        value: https://n8n.srv1710717.hstgr.cloud/webhook/48fd30e2-86e0-4bc8-b483-a0f961d2d144
      - key: N8N_PRICE_WEBHOOK_URL
        value: https://n8n.srv1710717.hstgr.cloud/webhook/4907eca7-65ca-41d2-a128-f345821b73ac
      - key: N8N_LOW_STOCK_WEBHOOK_URL
        value: https://n8n.srv1710717.hstgr.cloud/webhook/f631dfff-17ac-4cf5-82a4-b05ff21b1aad
      - key: N8N_TELEGRAM_WEBHOOK_URL
        value: https://n8n.srv1710717.hstgr.cloud/webhook-test/c002b8f1-a120-48d0-b526-1aafabbb54a1
